server:
  port: 3000
zuul:
  routes:
    item:
      path: /api/item/**
      service-id: item
      #url: http://localhost:3001
      stripPrefix: false
    user:
      path: /api/user/**
      service-id: user
      #url: http://localhost:3001
      stripPrefix: false
    purchase:
      path: /api/purchase/**
      service-id: purchase
      #url: http://localhost:3001
      stripPrefix: false
  sensitive-headers: 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/