server:
  port: 3000
zuul:
  routes:
    emart:
      path: /api/**
      service-id: emart
      #url: http://localhost:3001
      stripPrefix: false
  sensitive-headers: 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/