server:
  port: 3000
spring:
  datasource:
    url: jdbc:h2:file:./data/eMart
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h
  jpa:
    hibernate:
      ddlAuto: update
      dialect: org.hibernate.dialect.H2Dialect
    show_sql: true
    format_sql: true