server:
  port: 3001
spring:
  application:
    name: item
  datasource:
    url: jdbc:h2:file:./data/eMart
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h
  jpa:
    hibernate:
      ddlAuto: update
      dialect: org.hibernate.dialect.H2Dialect
    show_sql: true
    format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://docker.for.mac.host.internal:8761/eureka/
  instance:
    hostname: localhost
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic